"""added userId and user table

Revision ID: 71f56d0be767
Revises: e55fef47b83a
Create Date: 2021-05-13 15:48:07.854098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f56d0be767'
down_revision = 'e55fef47b83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.drop_column('packages', 'sender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('sender', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('users')
    # ### end Alembic commands ###
