"""added userId and user table v2

Revision ID: 976550ecc08d
Revises: 71f56d0be767
Create Date: 2021-05-13 15:52:13.825814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976550ecc08d'
down_revision = '71f56d0be767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'packages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.drop_column('packages', 'sender_id')
    # ### end Alembic commands ###
